In [4]:
import pandas as pd
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()

In [6]:
type(iris)

sklearn.utils.Bunch

In [7]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [8]:
type(iris.data)

numpy.ndarray

In [9]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [11]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [12]:
df['target']= iris.target

In [13]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [14]:
df['ID'] = df.index

In [15]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  ID  
0       0   0  
1       0   1  
2       0   2  
3       0   3  
4       0   4

In [16]:
df['Group'] = ['B' if col == 1 else 'A' for col in df['ID']%2]
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  ID Group  
0       0   0     A  
1       0   1     B  
2       0   2     A  
3       0   3     B  
4       0   4     A

In [17]:
df['Sum.Length'] = df['sepal length (cm)'] + df['petal length (cm)']
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  ID Group  Sum.Length  
0       0   0     A         6.5  
1       0   1     B         6.3  
2       0   2     A         6.0  
3       0   3     B         6.1  
4       0   4     A         6.4

In [18]:
raw_data = {'id' : ['s1', 's2', 's3', 's4', 's5', 's6'],
           'score': [55, 90, 85, 71, 63, 99]}
df = pd.DataFrame(raw_data)
df.head()

id  score
0  s1     55
1  s2     90
2  s3     85
3  s4     71
4  s5     63

In [19]:
df['grade'] = '수'
df.loc[df['score'] < 90, 'grade'] = '우'
df.loc[df['score'] < 80, 'grade'] = '미'
df.loc[df['score'] < 70, 'grade'] = '양'
df.loc[df['score'] < 60, 'grade'] = '가'
df.head()

id  score grade
0  s1     55     가
1  s2     90     수
2  s3     85     우
3  s4     71     미
4  s5     63     양

In [20]:
df = pd.read_csv("USArrests.csv", index_col= 0)
df.head()

Murder  Assault  UrbanPop  Rape
Alabama       13.2      236        58  21.2
Alaska        10.0      263        48  44.5
Arizona        8.1      294        80  31.0
Arkansas       8.8      190        50  19.5
California     9.0      276        91  40.6

In [21]:
df.corr()

Murder   Assault  UrbanPop      Rape
Murder    1.000000  0.801873  0.069573  0.563579
Assault   0.801873  1.000000  0.258872  0.665241
UrbanPop  0.069573  0.258872  1.000000  0.411341
Rape      0.563579  0.665241  0.411341  1.000000

In [22]:
import pandas as pd
import numpy as np

# 시각화 Library
import matplotlib.pyplot as plt
import seaborn as sns

# Sklearn에 있는 기본 데이터셋을 가져오기 위한
from sklearn import datasets

# sklearn의 PCA를 통해서 쉽게 PCA 적용가능
from sklearn.decomposition import PCA

In [25]:
pca = PCA()
pca.fit(df)
PC_score = pca.transform(df)
PC_score[:5]

array([[ 64.80216368,  11.4480074 ,  -2.49493284,   2.40790093],
       [ 92.82745016,  17.9829427 ,  20.12657487,  -4.09404703],
       [124.06821629,  -8.83040304,  -1.68744836,  -4.3536852 ],
       [ 18.34003541,  16.70391138,   0.21018936,  -0.5209936 ],
       [107.42295313, -22.52006977,   6.74587299,  -2.8118259 ]])

In [26]:
pca.components_

array([[ 0.04170432,  0.99522128,  0.04633575,  0.0751555 ],
       [ 0.04482166,  0.05876003, -0.97685748, -0.20071807],
       [ 0.07989066, -0.06756974, -0.20054629,  0.97408059],
       [ 0.99492173, -0.0389383 ,  0.05816914, -0.07232502]])

In [28]:
pca.explained_variance_

array([7.01111485e+03, 2.01992366e+02, 4.21126508e+01, 6.16424618e+00])

In [31]:
pca.explained_variance_ratio_

array([9.65534221e-01, 2.78173366e-02, 5.79953492e-03, 8.48907879e-04])

In [46]:
t = ['%0.2f ' % (i*100) for i in pca.explained_variance_ratio_]
t

['96.55 ', '2.78 ', '0.58 ', '0.08 ']