In [2]:
import pandas as pd
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [6]:
type(iris.data)

numpy.ndarray

In [7]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
df['target']= iris.target

In [11]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [12]:
df['ID'] = df.index

In [13]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  ID  
0       0   0  
1       0   1  
2       0   2  
3       0   3  
4       0   4

In [14]:
df['Group'] = ['B' if col == 1 else 'A' for col in df['ID']%2]
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  ID Group  
0       0   0     A  
1       0   1     B  
2       0   2     A  
3       0   3     B  
4       0   4     A

In [15]:
df['Sum.Length'] = df['sepal length (cm)'] + df['petal length (cm)']
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  ID Group  Sum.Length  
0       0   0     A         6.5  
1       0   1     B         6.3  
2       0   2     A         6.0  
3       0   3     B         6.1  
4       0   4     A         6.4

In [16]:
raw_data = {'id' : ['s1', 's2', 's3', 's4', 's5', 's6'],
           'score': [55, 90, 85, 71, 63, 99]}
df = pd.DataFrame(raw_data)
df.head()

id  score
0  s1     55
1  s2     90
2  s3     85
3  s4     71
4  s5     63

In [17]:
df['grade'] = '수'
df.loc[df['score'] < 90, 'grade'] = '우'
df.loc[df['score'] < 80, 'grade'] = '미'
df.loc[df['score'] < 70, 'grade'] = '양'
df.loc[df['score'] < 60, 'grade'] = '가'
df.head()

id  score grade
0  s1     55     가
1  s2     90     수
2  s3     85     우
3  s4     71     미
4  s5     63     양

In [18]:
df = pd.read_csv("USArrests.csv", index_col= 0)
df.head()

Murder  Assault  UrbanPop  Rape
Alabama       13.2      236        58  21.2
Alaska        10.0      263        48  44.5
Arizona        8.1      294        80  31.0
Arkansas       8.8      190        50  19.5
California     9.0      276        91  40.6

In [19]:
df.corr()

Murder   Assault  UrbanPop      Rape
Murder    1.000000  0.801873  0.069573  0.563579
Assault   0.801873  1.000000  0.258872  0.665241
UrbanPop  0.069573  0.258872  1.000000  0.411341
Rape      0.563579  0.665241  0.411341  1.000000

In [20]:
import pandas as pd
import numpy as np

# 시각화 Library
import matplotlib.pyplot as plt
import seaborn as sns

# Sklearn에 있는 기본 데이터셋을 가져오기 위한
from sklearn import datasets

# sklearn의 PCA를 통해서 쉽게 PCA 적용가능
from sklearn.decomposition import PCA

In [21]:
pca = PCA()
pca.fit(df)
PC_score = pca.transform(df)
PC_score[:5]

array([[ 64.80216368,  11.4480074 ,  -2.49493284,   2.40790093],
       [ 92.82745016,  17.9829427 ,  20.12657487,  -4.09404703],
       [124.06821629,  -8.83040304,  -1.68744836,  -4.3536852 ],
       [ 18.34003541,  16.70391138,   0.21018936,  -0.5209936 ],
       [107.42295313, -22.52006977,   6.74587299,  -2.8118259 ]])

In [22]:
pca.components_

array([[ 0.04170432,  0.99522128,  0.04633575,  0.0751555 ],
       [ 0.04482166,  0.05876003, -0.97685748, -0.20071807],
       [ 0.07989066, -0.06756974, -0.20054629,  0.97408059],
       [ 0.99492173, -0.0389383 ,  0.05816914, -0.07232502]])

In [23]:
pca.explained_variance_

array([7.01111485e+03, 2.01992366e+02, 4.21126508e+01, 6.16424618e+00])

In [24]:
pca.explained_variance_ratio_

array([9.65534221e-01, 2.78173366e-02, 5.79953492e-03, 8.48907879e-04])

In [25]:
t = ['%0.2f ' % (i*100) for i in pca.explained_variance_ratio_]
t

['96.55 ', '2.78 ', '0.58 ', '0.08 ']

In [27]:
swiss = pd.read_csv("swiss.csv")
swiss.head()

Unnamed: 0  Fertility  Agriculture  Examination  Education  Catholic  \
0    Courtelary       80.2         17.0           15         12      9.96   
1      Delemont       83.1         45.1            6          9     84.84   
2  Franches-Mnt       92.5         39.7            5          5     93.40   
3       Moutier       85.8         36.5           12          7     33.77   
4    Neuveville       76.9         43.5           17         15      5.16   

   Infant.Mortality  
0              22.2  
1              22.2  
2              20.2  
3              20.3  
4              20.6

In [29]:
for col in swiss.columns[1:]:
    swiss[col] = (swiss[col] - min(swiss[col]))/(max(swiss[col])-min(swiss[col]))

In [30]:
swiss.describe()

Fertility  Agriculture  Examination  Education   Catholic  \
count  47.000000    47.000000    47.000000  47.000000  47.000000   
mean    0.611175     0.558865     0.396746   0.191899   0.398506   
std     0.217247     0.256624     0.234644   0.184912   0.426212   
min     0.000000     0.000000     0.000000   0.000000   0.000000   
25%     0.516522     0.392090     0.264706   0.096154   0.031119   
50%     0.615652     0.597740     0.382353   0.134615   0.132754   
75%     0.755652     0.750847     0.558824   0.211538   0.929739   
max     1.000000     1.000000     1.000000   1.000000   1.000000   

       Infant.Mortality  
count         47.000000  
mean           0.578643  
std            0.184348  
min            0.000000  
25%            0.465190  
50%            0.582278  
75%            0.689873  
max            1.000000

In [31]:
dir(swiss)

['Agriculture',
 'Catholic',
 'Education',
 'Examination',
 'Fertility',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__